# Generated by Django 4.2.3 on 2023-08-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Our_Shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
